# Generated by Django 3.1.4 on 2020-12-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.member'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='recentview',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.member'),
        ),
        migrations.AddField(
            model_name='recentview',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='character_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.character'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
