# Generated by Django 3.1.4 on 2020-12-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201217_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_rate',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
