# Generated by Django 3.1.4 on 2020-12-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201217_1311'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
