# Generated by Django 3.1.4 on 2020-12-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201217_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='character',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
