# Generated by Django 3.1.4 on 2020-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201216_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
