# Generated by Django 3.1.4 on 2020-12-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201217_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='character',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
