# Generated by Django 3.1.4 on 2020-12-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201220_0420'),
        ('product', '0005_auto_20201219_1324'),
    ]

    operations = [
    ]
