# Generated by Django 3.1.4 on 2020-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nickname', models.CharField(max_length=20)),
                ('privacy_agreement', models.BooleanField()),
                ('anonymous', models.BooleanField()),
                ('random_number', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
                ('board', models.ManyToManyField(through='board.BoardLike', to='board.Board')),
                ('comment', models.ManyToManyField(through='board.CommentLike', to='board.Comment')),
                ('product', models.ManyToManyField(through='product.RecentView', to='product.Product')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
