# Generated by Django 3.1.4 on 2020-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201220_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='random_token',
            field=models.IntegerField(default=0),
        ),
    ]
