# Generated by Django 3.1.4 on 2020-12-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201222_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='random_token',
            field=models.IntegerField(null=True),
        ),
    ]
