# Generated by Django 3.1.4 on 2020-12-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20201217_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardlike',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='boardlike',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='member_id',
            new_name='member',
        ),
    ]
