# Generated by Django 3.1.4 on 2020-12-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0003_auto_20201216_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=45)),
                ('detail_address', models.CharField(max_length=45)),
                ('default', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'orderstatuses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_pay_id', models.CharField(max_length=45)),
                ('virtual_account', models.CharField(max_length=45)),
                ('member', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.member')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'paymentstatuses',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('member', models.ManyToManyField(through='order.Payment', to='user.Member')),
            ],
            options={
                'db_table': 'paymenttypes',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payments_status',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.paymentstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payments_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.paymenttype'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=45)),
                ('delivery_message', models.CharField(max_length=500)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.address')),
                ('member', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.member')),
                ('order_status', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus')),
                ('payments', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.payment')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='member_id',
            field=models.ManyToManyField(through='order.Order', to='user.Member'),
        ),
    ]
