# Generated by Django 3.1.4 on 2020-12-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='member',
            field=models.ManyToManyField(through='order.Payment', to='user.Member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payments_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.paymentstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payments_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.paymenttype'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='member_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.member'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='payments_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.payment'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='address',
            name='member_id',
            field=models.ManyToManyField(through='order.Order', to='user.Member'),
        ),
    ]
