# Generated by Django 3.1.4 on 2020-12-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201220_0420'),
        ('order', '0005_auto_20201220_1600'),
    ]

    operations = [
    ]
